# Please read the installation instructions: https://github.com/Simonsator/Party-API-For-Spigot/wiki/Installation
# Either set it to redis or mysql. Please read the installation instructions: https://github.com/Simonsator/Party-API-For-Spigot/wiki/Installation
PartyDataTransferMethod: 'None'
Redis:
  Host: 'localhost'
  Password: ''
  Port: 6379
